FEATURE: Update ligand data from GTP
protwis/protwis pull request #239
Opened 2020-11-12 12:49 UTC by AlibekMamyrbekov

Update ligands data using GTP data:
1) update ligands
2) update ligand assays
3) update endogenous ligands

2020-11-16 13:15 UTC, AJK-dev requested changes
@AlibekMamyrbekov: There are some potential issues, could you take a look at the comments and then let's book a meeting

2020-11-16 13:15 UTC, AJK-dev commented on tools/management/commands/get_gtp_ligands.py
> +    def get_gpcrs(self):
Example are the orphans

2020-11-16 15:22 UTC, AJK-dev commented on ligand/models.py
> +class LigandReceptorStatistics(models.Model):
Discussed, need further specifications for the selectivity index. Then update this table

2020-11-16 15:28 UTC, AJK-dev commented on tools/management/commands/get_gtp_ligands.py
> +    def get_gpcrs(self):
Add a check for the orphan and other level:
`{
  "familyId" : 115,
  "name" : "Orphan and other 7TM receptors",
  "targetIds" : [ ],
  "parentFamilyIds" : [ 694 ],
  "subFamilyIds" : [ 16, 706, 18, 975, 116, 117, 113 ]
}`

2020-11-18 13:23 UTC, AlibekMamyrbekov reviewed
DONE

2020-11-18 13:32 UTC, AlibekMamyrbekov commented on tools/management/commands/get_gtp_ligands.py
> +        for entry in response.json():
DONE

2021-01-18 08:00 UTC, closed without merging

2021-01-18 08:01 UTC, AlibekMamyrbekov commented
major refactoring