UPDATE: Bias build scripts merge
protwis/protwis pull request #282
Opened 2021-01-18 11:34 UTC by AlibekMamyrbekov

1. Changed bias excel file processing
2. Merged several scripts
3. Temporarily removed chembl bias script

2021-01-25 19:51 UTC, AJK-dev commented
Great to see that you've addressed all the Codacy stuff!
Could you do two more things: 
- Remove the 20 ligand model migrations and create one clean one?
- Re-enable the caching of the ligand statistics page?

2021-01-26 08:52 UTC, AlibekMamyrbekov commented
> Great to see that you've addressed all the Codacy stuff!
> Could you do two more things:
> 
> * Remove the 20 ligand model migrations and create one clean one? - done
> * Re-enable the caching of the ligand statistics page? - done

2021-02-09 18:09 UTC, esguerra requested changes
Some minor issues like missing `</a>` and unclosed }

2021-02-09 18:09 UTC, esguerra commented on tools/management/commands/upload_excel_bias.py
> +    structure_data_dir = os.sep.join([settings.DATA_DIR, 'ligand_data', 'bias_data','excel'])
Remember to put that data in the gpcrdb_data repo and make a pull request.

2021-02-09 18:10 UTC, esguerra commented on ligand/templates/target_details_compact.html
> +	}
} shouldn't be there.

2021-02-09 18:11 UTC, esguerra reviewed
still one more running } at taget_details_compact.html

2021-02-09 18:16 UTC, AlibekMamyrbekov commented on ligand/templates/ligand_info.html
> +			width: 70%px;
LoL, what a coincidence of both in same  place

2021-02-10 07:47 UTC, AlibekMamyrbekov reviewed
I am not sure about "quote" in ligand models as i was not using it.  
Html files will be submitted in separate pull requests with corresponding changes in views and model

2021-02-10 07:47 UTC, AlibekMamyrbekov commented on ligand/models.py
>  import json
I am not sure about it, as this part was made by Christian

2021-02-12 08:49 UTC, AJK-dev commented
I deleted the dev branch to start fresh from master, but thereby also closed your PR. Oops! 😨

2021-02-12 08:50 UTC, esguerra commented
> I deleted the dev branch to start fresh from master, but thereby also closed your PR. Oops! 😨

I think this merge request might not be ready yet.

2021-02-12 09:21 UTC, esguerra commented
I have reopened this pull request but think that we should discuss closing it and splitting it into separate pull requests.
This one is mixing changes in the ligand pages and biased signaling pages, making it difficult to separate possible issues if they all come into one pull request.
In my local deployment the selection capability in the ligand pages is lost. Such issues would be easier to track down if split into separate pull requests, as stated before.

2021-02-14 18:06 UTC, closed without merging

2021-02-14 18:06 UTC, AlibekMamyrbekov commented
separate into several prs