ARRESTINDB updates and fixes
protwis/protwis pull request #586
Opened 2024-11-28 15:38 UTC by prossotto

ARRESTINDB updates and fixes

2025-01-13 11:53 UTC, pszgaspar requested changes
Hey, very big update so lots of moving pieces. I flagged a couple things which I am unsure of, please have a look.

2025-01-13 11:53 UTC, pszgaspar commented on protwis/settings.py
> +SMILES_MAX_LENGTH = 200
These two variables SMILES_MAX_LENGTH and PYTHON_SMILES_VALIDATION are duplicates

2025-01-13 11:53 UTC, pszgaspar commented on protein/migrations/0020_merge_20250110_0926.py
Do you remember how this merged migration file came to be? What was in the 0019_proteinsegment_domain migration file? I'd prefer a separate clean migration file 0020_...

2025-01-13 11:53 UTC, pszgaspar commented on protwis/context_processors.py
> +    domain_switches = {"gpcrdbx.org" : "gpcr", "gproteindbx.org:8000" : "gprotein", "arrestindbx.org:8000": "arrestin", "biasedsignalingatlas.org": "biasedsignalingatlas"}
why do the ports need to be specified here?

2025-01-13 11:53 UTC, pszgaspar commented on protwis/settings_local_development.py
> +DATA_DIR = '/Users/vtk842/' + SITE_NAME
revert this one please

2025-01-13 11:53 UTC, pszgaspar commented on protwis/settings_local_production.py
> +DATA_DIR = '/Users/vtk842/' + SITE_NAME
revert this too

2025-01-13 11:53 UTC, pszgaspar commented on signprot/templates/signprot/coupling_browser_deprecated.html
> +                    <th>Phys. /<br>SurrXXXXXX.</th>
thos looks like a typo

2025-01-13 11:53 UTC, pszgaspar commented on signprot/views.py
> +            (Q(family__parent__parent__parent__slug__startswith='001')
please double check these slugs if they still reference the class you want. And then change the query to query on the class name instead

2025-01-13 11:53 UTC, pszgaspar commented on signprot/views.py
> +    print("CALLEEEED")
remove this print please

2025-01-13 11:53 UTC, pszgaspar commented on static/home/js/datamapper.js
why is there a datamapper update in this PR? Please double-check if this is a legit update

2025-01-13 11:53 UTC, pszgaspar commented on static/home/js/g_protein_structure_browser.js
are these updates legit? Is this same js file used for the arrestin structure browser? I would guess not but then I am not sure what these updates are. Compare your local G protein structure browser with the main server

2025-01-13 11:53 UTC, pszgaspar commented on static/home/js/signprotmat.js
> +        // COLORED RESIDUE INTERACTION
is this commented section needed?

2025-01-13 11:53 UTC, pszgaspar commented on static/home/js/signprotmat.js
> +        // COLORED RESIDUE INTERACTION NOT
is this commented section needed?

2025-01-13 11:53 UTC, pszgaspar commented on structure/functions.py
> +                print('LINE')
please remove prints

2025-01-13 11:53 UTC, pszgaspar commented on structure/templates/g_protein_structure_browser.html
Please also check if these changes are needed. There is definitely something that is a reversion (changing Physiological ligand back to endogenous). Also, why is there an arrestin block here for the G protein structure browser?

2025-01-13 11:53 UTC, pszgaspar commented on structure/templates/superposition_workflow_upload_file_form.html
> +          {% elif source == 'gprot' %}
is this source check correct? Shouldn't it be arrestin?

2025-01-13 11:53 UTC, pszgaspar commented on structure/templates/superposition_workflow_upload_file_form.html
> +          {% elif source == 'gprot' %}
same source check question

2025-01-13 11:53 UTC, pszgaspar commented on structure/urls.py
please clean up this file. There's an ERASE comment, quite a lot of commented lines, not sure what is going on

2025-01-14 12:33 UTC, prossotto commented on structure/templates/g_protein_structure_browser.html
Only for the section of arrestin, I reverted everything related to Gprotein structure browser. (No push yet)

2025-01-14 12:39 UTC, prossotto commented on static/home/js/g_protein_structure_browser.js
Just the changes for the arrestin section.

2025-01-14 12:39 UTC, prossotto commented on static/home/js/datamapper.js
Noup, I think this happened, when I merge the dev_build to the arrestindb branch, when pushing it to my upstream arrestindb, It may have interpret the changes as mine. I put it as it is in the dev_build, I think that should do it.

2025-01-14 12:42 UTC, prossotto commented on protein/migrations/0020_merge_20250110_0926.py
Yep, I had a 0019 already, so I merge them, but I just made my 0019 as 0020 and kep the 0019 from dev_build as the 0019, it should be cleaner.

2025-01-14 12:49 UTC, prossotto commented on structure/templates/superposition_workflow_upload_file_form.html
> +          {% elif source == 'gprot' %}
I think the if-else its correct, if it is gprot it will take from g_protein_structure_browser... url, and just "else" has to be from arrestin, which is below.

2025-01-16 09:04 UTC, pszgaspar requested changes
thanks for the fixes, I found a few more minor things, please have a look

2025-01-16 09:04 UTC, pszgaspar commented on protwis/context_processors.py
> +    domain_switches = {"gpcrdbx.org" : "gpcr", "gproteindbx.org" : "gprotein", "arrestindbx.org": "arrestin", "biasedsignalingatlas.org": "biasedsignalingatlas"}
the x remained there, I believe that is not needed

2025-01-16 09:04 UTC, pszgaspar commented on ligand/views.py
there are no changes in this file, only not needed white space and line break differences. Please revert this

2025-01-16 09:04 UTC, pszgaspar commented on build/management/commands/build_coupling_data.py
> +                        # try:
is this big commented section needed? Can it be removed?

2025-01-16 09:04 UTC, pszgaspar commented on build/management/commands/build_coupling_data.py
there are a lot of print statements added to this file. Could you remove the unnecessary ones?

2025-01-16 09:04 UTC, pszgaspar commented on alignment/templates/alignment/alignment.html
unnecessary line breaks, please revert this file

2025-01-16 09:04 UTC, pszgaspar commented on structure/urls.py
> +    # url(r'^complex_models/(?P<modelname>\w+)-(?P<signprot>\w+)$', cache_page(60*60*24*7)(ComplexModelDetails), name='complex_model_details'),
there are a lot of these commented urls. Are these needed?

2025-01-16 14:16 UTC, pszgaspar approved these changes
thanks for the cleanup

2025-10-07 13:09 UTC, closed without merging